<div class="span3">&nbsp;</div>
<div class="span6">
      <div class="widget">
        <div class="widget-header">
          <h3>Clientes</h3>
        </div>
        <!-- /widget-header -->
        <div class="widget-content">
          <div class="shortcuts"> 
              <a href="clientes/create" class="shortcut"><i class="shortcut-icon icon-user"></i><span class="shortcut-label">Registro de Clientes</span> </a>
              <a href="tipos_documentos/create" class="shortcut"><i class="shortcut-icon icon-list-alt"></i><span class="shortcut-label">Tipo de Identificación</span> </a>
              <a href="tipos_clientes/create" class="shortcut"><i class="shortcut-icon icon-male"></i> <span class="shortcut-label">Tipos de Clientes</span> </a>
              <a href="condicion_pago/create" class="shortcut"> <i class="shortcut-icon icon-dollar"></i><span class="shortcut-label">Condición de Pago</span> </a>
          </div>
          <!-- /shortcuts --> 
        </div>
        <!-- /widget-content --> 
</div>
<div class="span3">&nbsp;</div>

