<div class="span12">
	<h2>Tipos de Clientes</h2>
</div>

<div class="span12"><?php View::content(); ?><br></div>

    <div class="span2">&nbsp;</div>
    
    <?php echo Form::open(); // por defecto llama a la misma url ?>
    
    <div class="span5">
        
        <label>Tipo de Cliente
            <?php echo Form::text('tipo_cliente') ?></label>
     
            <label>Descripción
            <?php echo Form::text('descripcion') ?></label>
            
            <label>Prefijo
            <?php echo Form::text('prefijo') ?></label>
            
            IVA
            <?php echo Form::check('iva','1','') ?><br>
            
            Suplemento
            <?php echo Form::check('spto','1','') ?><br>
            
            Descuento
            <?php echo Form::check('dcto','1','') ?><br>
            
            <label>Comentario
            <?php echo Form::textarea('comentario','rows=5') ?></label>
            
    </div>
    
    <div class="span3">
            <label>Clientes Registrados</label>
            <textarea name="docs" rows="10" readonly id="docs">
                <?php 	
                foreach ($listaTipos as $items => $item) :
			echo $item->tipo_cliente; echo "\n";
                    endforeach; ?></textarea>
    </div>       
    
    <div class="span2">&nbsp;</div>

<div class="span12" style="text-align:center"><?php echo Form::submit('Agregar','class="btn btn-primary"') ?></div>
        
<?php echo Form::close() ?> 