<?php View::content(); ?>

<?php echo Form::open(); // por defecto llama a la misma url ?>
 <div class="span6">
     <fieldset style="border: 2px solid #ccc;">
         <table>
             <tr>
                 <th>Identificaci&oacute;n</th>
                 <td>
                     <?php
                        //echo Form::dbSelect('clientes.idtipodoc','tipo_doc', array('tipo_documentos','getSelect'),'Seleccione',array('onchange'=>'buscarCliente(this)'));
                        echo Form::dbSelect('clientes.idtipodoc','tipo_doc', array('tipo_documentos','getSelect'),'Seleccione' ,array('onchange'=>'accionRif(this)'));
                        echo Form::text('clientes.identificacion');
                     ?>
                     <span id="div_digito_rif" style="display: none"> - <?php echo Form::text('digito_rif', array('size'=>'1', 'id'=>'digito_rif',  'maxlenght'=>'1')); ?></span>
                     <?php echo Form::button("Siguiente", array('onclick'=>'buscarCliente()'))?>
                 </td>
             </tr>
         </table>
     </fieldset> 
     
     <br>       
</div>
<div class="span7" id='form' style='display: '>
    <fieldset style="border: 1px solid #ccc;"><legend>Datos Generales</legend>
    <table width="100%" border='1'>
        <tr>
            <th align='left'>
                    <?php echo Form::hidden('clientes.idcliente') ?>Nombre
            </th>
            <td><?php echo Form::text('clientes.nombre') ?></td>
            <th align='left'>Apellido </th> 
            <td><?php echo Form::text('clientes.apellido') ?></td>
        </tr> 
        <t>
            <th align='left'>Direccion </th>
            <td>
                <?php echo Form::textarea('clientes.direccion','rows=5') ?>
            </td>  
           
            <th align='left'>Telefono</th>
            <td>
                 <?php echo Form::text('clientes.telefono') ?>
            </td>
        </t>
        <tr>
            <th>Tipo de Cliente
                    
            </th>
            <td colspan="4">
                <?php
                echo Form::dbSelect('clientes.idtipocliente','tipo_cliente', array('tipo_clientes','getSelect'));
                ?> 
            </td>
        </tr>
    </table>   
</fieldset>      
  <?php //echo Form::submit('Agregar',array('id'=>'bt_accion')) ?>      
</div>
 
        
 
<?php echo Form::close() ?>

<script>
    
    function accionRif(str){
       var tipo_doc = $("#clientes_idtipodoc option:selected").html();
       if(tipo_doc.toUpperCase() == 'RIF'){
           document.getElementById('div_digito_rif').style.display = '';
           
       }else{
           document.getElementById('div_digito_rif').style.display = 'none';
           document.getElementById('digito_rif').value = '';
       }
    }
    
    function  buscarCliente(){
        if($('#clientes_idtipodoc').val() == ''){
            alert('Seleccione el tipo de documento');
            return false;
        }
        if($('#clientes_identificacion').val() == ''){
            alert('Ingrese el numero de identificacion');
            return false;
        }
            
	var identificacion = $('#clientes_identificacion').val();
        var idtipodoc = $('#clientes_idtipodoc').val();
        if($('#digito_rif').val() != '')
            identificacion = identificacion + "-" + $('#digito_rif').val();
        
        $.ajax({
        dataType:"json",
        type: "POST",
        url: "<?php echo PUBLIC_PATH . 'clientes/buscarCliente/'; ?>",
        data: "idtipodoc=" + idtipodoc + "&identificacion=" + identificacion,
        success: cargarDatos
        });
        
        function cargarDatos(cliente) {
                //$("#clientes_accion").val(cliente.idcliente); 
                $("#clientes_idcliente").val(cliente.idcliente); 
                //$("#clientes_identificacion").val(cliente.identificacion); 
                $("#clientes_nombre").val(cliente.nombre); 
                $("#clientes_apellido").val(cliente.apellido); 
                $("#clientes_telefono").val(cliente.telefono); 
                $("#clientes_direccion").val(cliente.direccion); 
                $("#clientes_idtipocliente").val(cliente.idtipocliente); 
                //$("#clientes_idtipodoc").val(cliente.idtipodoc); 
               
                
                //muestra el formulario
                document.getElementById('form').style.display = '';
            
        }   
    }    
        
        //});
        /*
        if(num_identif != ''){
            var rowSelected=$("body").find('#' + 'form' )
            //rowSelected.html('<td colspan="4"> <img src="<?php //echo PUBLIC_PATH ?>/img/ui/ajax-loader.gif" /> Eliminando ...</td>');
            rowSelected.html('<span> <img src="<?php //echo PUBLIC_PATH ?>/img/ui/ajax-loader.gif" /> Carcgando ...</span>');
            $.ajax({
            type: "POST",
            dataType:"html",
            //type: "GET",
            url: "<?php //echo PUBLIC_PATH . 'clientes/tipos' ?>",
            success:
            function(data){
                $(rowSelected).hide();
                $('#form').html(data);
            }
            });
         }else{
            alert('Debe ingresar el numero de identificacion');
            document.getElementById("clientes_identificacion").focus;
            return;
         }
        
        */
        
       /*
        for(i=0; i<theForm.elements.length; i++){
            var alertText = ""
                alertText = "Element id: " + theForm.elements[i].id + "\n"
               
                alertText = "Element Name: " + theForm.elements[i].name + "\n"
                
                alertText += "Element Type: " + theForm.elements[i].type + "\n"

                if(theForm.elements[i].type == "text" || theForm.elements[i].type == "textarea" || theForm.elements[i].type == "button"){
                alertText += "Element Value: " + theForm.elements[i].value + "\n"
                }
                else if(theForm.elements[i].type == "checkbox"){
                alertText += "Element Checked? " + theForm.elements[i].checked + "\n"
                }
                else if(theForm.elements[i].type == "select-one"){
                alertText += "Selected Option's Text: " + theForm.elements[i].options[theForm.elements[i].selectedIndex].text + "\n"
                }
            alert(alertText)
        }
        */
   
        /*
        var rowSelected=$("body").find('#' + 'identificacion');
        alert(rowSelected.val);
        alert('entro');*/

        /*
        var rowSelected=$("body").find('#' + 'identificacion' )


        rowSelected.html('<td colspan="4"> <img src="<?php //echo PUBLIC_PATH ?>/img/ui/ajax-loader.gif" /> Eliminando ...</td>');
        $.ajax({
        type: "GET",
        url: "<?php //echo PUBLIC_PATH . 'tipos_documentos/borrar/' ?>" + id,
        success:
        function(data){
        $(rowSelected).hide();
        $('#list').html(data);
        }

        });*/
        /*if(document.getElementByName('clientes[identificacion]').value == ''){
            alert('esta ');
        }*/
        
   


    </script>