<div class="account-container">
	<div class="content clearfix">
    <?php View::content(); ?>
    <?php echo Form::open("usuarios/login"); ?>
		
			<h1>Inicio de Sesión</h1>		
			
			<div class="login-fields">
				
				<p>Introduzca sus datos de sesión</p>
				
				<div class="field">
                	<?php echo Form::label("Usuario","usuario"); ?>
					<?php echo Form::text("usuario",'value="" placeholder="Usuario" class="login username-field"'); ?>
				</div> <!-- /field -->
				
				<div class="field">
                	<?php echo Form::label("Password","password"); ?>
					<?php echo Form::pass("password",'value="" placeholder="Password" class="login password-field"'); ?>
				</div> <!-- /password -->
				
			</div> <!-- /login-fields -->
			
			<div class="login-actions">
				
				<?php echo Form::submit("Ingresar",'class="button btn btn-success btn-large"'); ?>				
				
			</div> <!-- .actions -->
			
			
			
		<?php echo Form::close(); ?>


		
	</div> <!-- /content -->
 </div>
	    