
<div class="span12"><?php View::content(); ?><br></div>
    <div class="span12">
	<h2><?php echo $titulo;  ?></h2>
        <br>
    </div>

    <div class="span1">&nbsp;</div>
    
    <?php echo Form::open(); // por defecto llama a la misma url ?>
    
    <div class="span3">
    
    <fieldset>
        	<legend>Crear Producto</legend>
            <label>Tipo de Producto
            <?php echo Form::text('tipo_productos.tipo_prod') ?></label>
     
            <label>Descripción
            <?php echo Form::text('tipo_productos.descripcion') ?></label>
            
            <label>Identificador
            <?php echo Form::text('tipo_productos.identificador') ?></label>
            
            <br>
            <label>Comentario
            <?php echo Form::textarea('tipo_productos.comentario','rows=5') ?></label>
		</fieldset>
        
        <div class="centrado"><?php echo Form::submit('Agregar','class="btn btn-primary"') ?></div>
            
    </div>
    
    <div class="span1">&nbsp;</div>
    
    <div class="span7">
        <div id="list" >
        <?php View::partial('productos/list_tipo_productos',FALSE,array('list'=>$list))?>
        </div> 
    </div>       
        
<?php echo Form::close() ?> 

