
<div class="span12">
    <?php View::content(); ?><br>
	
</div>

<div class="span12">
    <h2><?php echo $titulo;  ?></h2>
    <br>
</div>

    <div class="span2">&nbsp;</div>
    
    <?php echo Form::open(); // por defecto llama a la misma url ?>
    
        <div id="div_create" class="span5">
            
            <?php echo Form::hidden('tipo_productos.idtipoprod') ?>
            <label>Tipo de Produto
            <?php echo Form::text('tipo_productos.tipo_prod') ?></label>
     
            <label>Descripción
            <?php echo Form::text('tipo_productos.descripcion') ?></label>
            
            <label>Identificador
            <?php echo Form::text('tipo_productos.identificador') ?></label>
            
            <br>
            <label>Comentario
            <?php echo Form::textarea('tipo_productos.comentario','rows=5') ?></label>
            
    </div>
    
    <div id="list" class="span3" style="width: 300px; height:400px;">
        <?php echo Html::link("tipo_productos/create", 'Crear nuevo') ?>
        <br>
        <?php View::partial('productos/list_tipo_productos',FALSE,array('list'=>$list))?>
    </div>     
    
    <div class="span2">&nbsp;</div>

    <div class="span12" style="text-align:center">
        <?php echo Form::submit('Actualizar','class="btn btn-primary"') ?>
        <?php echo Form::reset('Cancelar','class="btn btn-primary"') ?>
    </div>
        
<?php echo Form::close() ?> 

