
<div class="span12">
	<h2>Actualizacion de Tipo de Identificación</h2><br>
</div>

<div class="span12"><?php View::content(); ?><br></div>

<div class="span1">&nbsp;</div>

<?php echo Form::open(); // por defecto llama a la misma url ?>

<div id="div_create" class="span3">
    <?php echo Form::hidden('accion',null,'hola') ?>
    
    <fieldset>
    
            <label>Tipo de documento
            <?php echo Form::text('tipodoc.tipo_doc') ?>
            
            <?php echo Form::hidden('tipodoc.idtipodoc') ?>
            </label>
     
            <label>Descripción
            <?php echo Form::text('tipodoc.descripcion') ?></label>
            
            <label>Identificador
            <?php echo Form::text('tipodoc.identificador') ?></label>
            
            <label>Comentario
            <?php echo Form::textarea('tipodoc.comentario','rows=5') ?></label>
   </fieldset>    
</div>

<div class="span1">&nbsp;</div>

<div id="list" class="span4">
    <?php echo Html::link("tipos_documentos/create", 'Crear nuevo','class="btn btn-info"') ?>
    <br><br>
    <?php View::partial('clientes/list_tipo_documentos',FALSE,array('list'=>$list))?>
</div>     


<div class="span12" style="text-align:center">
    <?php echo Form::submit('Actualizar','class="btn btn-primary"') ?>
    <?php echo Form::reset('Cancelar','class="btn btn-cancel"') ?>
</div>
        
<?php 
echo Form::close() ?> 


<script type='javascript'>
/*
function borrar(id){
 var rowSelected=$("body").find('#' + 'c' + id)
 rowSelected.html('<td colspan="4"> <img src="<?php //echo PUBLIC_PATH ?>/img/ui/ajax-loader.gif" /> Eliminando ...</td>');
 $.ajax({
  type: "GET",
  url: "<?php //echo PUBLIC_PATH . 'tipos_documentos/borrar/' ?>" + id,
  success:
   function(data){
    $(rowSelected).hide();
    $('#list').html(data);
   }
  
 });
}*/
</script>


<script>
//cargarLista('1');

function cargarLista(page){
    
 //var rowSelected=$("body").find('#list')
 //rowSelected.html('<td colspan="4"> <img src="<?php //echo PUBLIC_PATH ?>/img/ui/ajax-loader.gif" /> cargando ...</td>');
  $.ajax({
  type: "GET",
  url: "<?php echo PUBLIC_PATH . 'tipos_documentos/lista'; ?>",
  success:
   function(data){
    //$(rowSelected).hide();
    $('#list').html(data);
   }
  
  
 });
}

</script>