<?php View::content(); ?>
<div id="resultado"></div>
<div class="span12">
     
    <h2>Facturación y Venta</h2>
     <br>
    <span style='font-size: 15px; font-weight: bold;' class="btn btn-primary">
    Punto de venta: <?php echo Session::get("puntoventa");?>
    </span>   

</div>

<?php //echo Ajax::form("resultado"); 
    echo Form::open();
?>
<div class="span5">
    
    <fieldset>
        <legend>Datos Generales</legend>
        
            Identificación
            <?php
                //echo Form::dbSelect('clientes.idtipodoc','tipo_doc', array('tipo_documentos','getSelect'),'Seleccione',array('onchange'=>'buscarCliente(this)'));
                echo Form::dbSelect('clientes.idtipodoc','tipo_doc', array('tipo_documentos','getSelect'),'Seleccione' ,array('onchange'=>'accionRif(this)'));
                echo Form::text('clientes.identificacion','size="20"');
            ?>
            <span id="div_digito_rif" style="display: none"> - <?php echo Form::text('digito_rif', array('size'=>'1', 'id'=>'digito_rif',  'maxlenght'=>'1')); ?></span>
            <?php echo Form::button("Siguiente", array('onclick'=>'buscarCliente()'))?>
            <table>   
                <tr>
                 <th align='left'>
                         <?php echo Form::hidden('clientes.idcliente') ?>Nombre
                 </th>
                 <td><?php echo Form::text('clientes.nombre') ?></td>
                 <th align='left'>Apellido </th> 
                 <td><?php echo Form::text('clientes.apellido') ?></td>
             </tr> 
             <t>
                 <th align='left'>Direccion </th>
                 <td>
                     <?php echo Form::textarea('clientes.direccion','rows=5') ?>
                 </td>  

                 <th align='left'>Telefono</th>
                 <td>
                      <?php echo Form::text('clientes.telefono') ?>
                 </td>
             </t>
             <tr>
                <th>Tipo de Cliente

                </th>
                <td colspan="4">
                    <?php
                    echo Form::dbSelect('clientes.idtipocliente','tipo_cliente', array('tipo_clientes','getSelect'));
                    ?> 
                </td>
            </tr>
            </table>
    </fieldset>
    
    <fieldset>
        
        <legend>Productos a Vender</legend>
        
        <div >
             Preparaciones
            <select name='elaborado[]' id='elaborado' multiple="true" size='10' onclick="agregarElaborados(this,'prep')" style="width: 200px;">
<!--                     <option value="">  </option>-->
                <?php
                foreach($elaborados as $items):
                    ?>
                  <option value='<?php echo $items->idproducto; ?>'> <?php echo $items->preparacion ."/ PVP:".$items->precio_sin_iva ."/ DISP:".$items->disp  ?>  </option>

                <?php endforeach; ?>
            </select>
        </div>
        
        <div >           
<!--           Filtrar Preparaciones
           <br>   
            Fecha desde &nbsp; <?php //echo Form::date('fe_desde') ?>  hasta &nbsp; <?php //echo Form::date('fe_hasta') ?>      
            <br>-->
            Productos 
            <select name='productos[]' id='productos' multiple="true" size='10' onclick="agregarElaborados(this,'prep')" style="width: 350px;">
             <?php
            foreach($productos as $items => $item):
                //$prod = $item->marca."/".$item->tipo_prod."/".$item->presentacion;
                $prod = $item->marca."/".$item->tipo_prod."/".$item->presentacion." / PVP:".$item->precio_sin_iva ."/ DISP:".$item->disp
                ?>
                <option value='<?php echo $item->idproducto ?>'> <?php echo $prod ?>  </option>

            <?php endforeach; ?>
            </select> 

            <input name="cant_row" id="cant_row" type="hidden" value="0">
        </div>
    </fieldset>
</div>

<div class="span1">&nbsp;</div>
    
<div class="span6">
       
        
        <fieldset> 
            <legend>Articulos</legend>
            <div style="overflow: auto; max-height:300px;">
            <table id="prod_detalle" class="table">
                <tbody>
                    <tr bgcolor='#cccccc'>
                        <td>Codigo</td>
                        <td>Articulo</td>
                        <td>Precio</td>
                        <td>Borrar</td>
                    </tr>
                </tbody>
            </table>
            </div>
        </fieldset>
        <br>
       <fieldset>
           
            <legend>Totalización</legend>
        
                Subtotal <?php echo Form::text('subtotal','readonly="true" size="10"') ?>

                IVA <?php echo Form::text('iva','onblur="totalizarTodo()" size="10"') ?>

                Total <?php echo Form::text('total', 'readonly="true" size="10"') ?>

        </fieldset>
        <br>
        <fieldset> 
            <legend>CONDICI&Oacute;N DE PAGO:</legend>
            <table width=200 border="1" class="table" style="width: 300px; height: 200px; font-size: 11px;">
                <tr>
                    <th>Efectico</th>
                    <td><?php echo Form::text("efectivo") ?></td>
                    <td><?php echo Form::check("ch_efectivo",'1') ?></td>
                </tr>    
                    <th>Cesta Ticket</th>
                    <td><?php echo Form::text("ticket") ?></td>
                    <td><?php echo Form::check("ch_ticket",'1') ?></td>
                <tr>
                </tr>
                    <th>D&eacute;bito</th>
                    <td><?php echo Form::text("debito") ?></td>
                    <td><?php echo Form::check("ch_debito",'1') ?></td>
                <tr>
                </tr>
                    <th>Tarjeta de Cr&eacute;dito</th>
                    <td><?php echo Form::text("tc") ?></td>
                    <td><?php echo Form::check("ch_tc",'1') ?></td>
                </tr>
                </tr>
                    <th>Cr&eacute;dito Oasis </th>
                    <td><?php echo Form::text("credito_oasis") ?></td>
                    <td><?php echo Form::check("ch_credito_oasis",'1') ?></td>
                </tr>
            </table>
        </fieldset>
        <br>
        <fieldset>   
            <div class="span2">&nbsp;</div>
                <br>
                ON/OFF:
                <?php
                    echo Form::check('ch_imprimir','1');
                ?>
            <div class="span3">
             <?php echo Form::submit('EFECTUAR VENTA',array('class'=>'btn btn-primary', 'onclick'=>'return validar();')); // ?>
            <?php echo Form::reset('CANCELAR',array('class'=>'btn btn-cancel')); // ?>  
                
<!--            <input type="submit" value="EFECTUAR VENTA" class="btn btn-primary" onclick="return validar();">    -->
<!--            <a href="#" class="btn btn-cancel">CANCELAR</a>-->
            </div>
        </fieldset>
</div>

<div id="prueba"></div>
<?php echo Form::close(); ?>
<script>
    function validar(){
//        if($('#cant_row').val() == ''){
//            alert('No hay articulos para factura');
//            return false;
//        }else{
//            if(!confirm('Esta seguro?'))
//               return false; 
//        }
    }
    
    function accionRif(str){
       var tipo_doc = $("#clientes_idtipodoc option:selected").html();
       if(tipo_doc.toUpperCase() == 'RIF'){
           document.getElementById('div_digito_rif').style.display = '';
           
       }else{
           document.getElementById('div_digito_rif').style.display = 'none';
           document.getElementById('digito_rif').value = '';
       }
    }
    
    function  buscarCliente(){
        if($('#clientes_idtipodoc').val() == ''){
            alert('Seleccione el tipo de documento');
            return false;
        }
        if($('#clientes_identificacion').val() == ''){
            alert('Ingrese el numero de identificacion');
            return false;
        }
            
	var identificacion = $('#clientes_identificacion').val();
        var idtipodoc = $('#clientes_idtipodoc').val();
        if($('#digito_rif').val() != '')
            identificacion = identificacion + "-" + $('#digito_rif').val();
        
        $.ajax({
        dataType:"json",
        type: "POST",
        url: "<?php echo PUBLIC_PATH . 'clientes/buscarCliente/'; ?>",
        data: "idtipodoc=" + idtipodoc + "&identificacion=" + identificacion,
        success: cargarDatos
        });
        
        function cargarDatos(cliente) {
                //$("#clientes_accion").val(cliente.idcliente); 
                $("#clientes_idcliente").val(cliente.idcliente); 
                //$("#clientes_identificacion").val(cliente.identificacion); 
                $("#clientes_nombre").val(cliente.nombre); 
                $("#clientes_apellido").val(cliente.apellido); 
                $("#clientes_telefono").val(cliente.telefono); 
                $("#clientes_direccion").val(cliente.direccion); 
                $("#clientes_idtipocliente").val(cliente.idtipocliente); 
                //$("#clientes_idtipodoc").val(cliente.idtipodoc); 
                
                //muestra el formulario
                document.getElementById('form').style.display = '';
            
        }   
    }
    
    function borrarProducto(linea){
        
        $("#prod_detalle tr:gt("+linea+")").remove();
        
//        var num_line = $('#cant_row').val(); 
//        for(var i=1; i<=num_line; i++){
//            if(is$(('#precio'+num_line)) ){
//                alert($('#precio'+num_line).val());
//            }  
//        }
        
//        
//        //alert(num_line);
//        
//        
        //$('#cant_row').val(num_line); 
    }
    
    function agregarElaborados(str, tipo){
        var num_line = $('#cant_row').val(); 
        /*
        for(var i=1; i<=num_line; i++){
          
            if(str.value == $('#idproducto'+i).val()){
                alert('Ya fue agregado esta opcion');
                return false;
            }
        }*/
        
        
        $.ajax({            
        dataType:"json",
        type: "POST",
        url: "<?php echo PUBLIC_PATH . 'ventas/getDetalleElaborados'; ?>",
        data: "idtipoprep="+str.value,
        success: function (detalle){
                
           //$("#prueba").html(html);
            num_line++;
            var producto = '';
            //var tipo_prod_final;
            if(tipo == 'prep'){
                producto = $('#elaborado option:selected').text();
                //tipo_prod_final =  'R';       
            }else{
                producto = $('#productos option:selected').text();
                //tipo_prod_final =  'P';  
            }  
            /*var preparacion = (tipo == 'prep' ? $('#elaborado option:selected').text() : $('#productos option:selected').text()); 
            //var tipo_prod_final (tipo == 'prep') ? 'R' : 'P');*/
        
            //var producto = preparacion //$('#productos option:selected').text();
            var idproducto = str.value; 
            var precio = (isNaN(parseFloat(detalle.precio)) ? 0 : parseFloat(detalle.precio)  );
           
            var td1 = "<td> <span id=txt_idproducto"+num_line + "> "+idproducto+" </span> </td>";
            var td2 = "<td><span id=txt_producto"+num_line + "> "+producto+" </span>\n\
                        <input name='idproducto"+num_line + "'  id='idproducto"+num_line + "' type='hidden' size='5' value='"+ idproducto +"'></td>";
            //alert(td1);
            var td3 = "<td> <span id=txt_precio"+num_line + "> "+precio+" </span>\n\
                        <input name='precio"+num_line + "' id='precio"+num_line + "' type='hidden' size='10' value='" + precio + "'> </td>";
           
            var td4 = "<td> <a href='#' id='borrar"+num_line + "' onclick='borrarProducto("+ num_line +");'>Borrar</a> </td>";
            
            var tr = td1 + td2 + td3 + td4;
            
            $('#prod_detalle> tbody:last').append('<tr bgcolor="#ffffff">'+ tr + '</tr>');    
                
            $('#cant_row').val(num_line); 
            
            //llama la funcion para totalizar la linea
            totalizarTodo(); 
        }
           
        });
    } 
    
    
    function totalizarTodo(){
        var num_line =  $("#cant_row").val();
        //alert(num_line);
        var subtotal = 0;
        var total = 0;
        var iva = 0;
        var total_iva = 0;
        var precio = 0;
        
        if(!isNaN(parseFloat($("#iva").val())))
            iva = parseFloat($("#iva").val());
        else
            iva = 0;
        
        for(var i=1; i<=num_line; i++){
            //total = parseFloat($("#total"+i).val());
            if(!isNaN(parseFloat($("#precio"+i).val())))
                precio = parseFloat($("#precio"+i).val());
            else
                precio = 0;
            
            subtotal += precio;
        }
        
        //calculo del total con iva
        total_iva = (subtotal * iva) / 100;
        
        total = subtotal + total_iva;
        
        $("#subtotal").val(subtotal);
        $("#total").val(total); 
    }
    
</script>



