<div class="span12">
<h2>Nueva Factura</h2>
</div>
 
<?php echo Form::open(); // por defecto llama a la misma url ?>
 <div class="span4">
 		<?php echo Form::hidden('idfactemp',NULL,$idfactemp->id) ?>
        <label>Tipo Cliente<?php $tipo = array('V','E','J','G');
		echo Form::select('tipo_fiscal',$tipo) ?></label><?php echo Form::hidden('idcliente') ?>
        <label>Cedula/RIF<?php echo Form::text('identificacion','onChange="buscaCliente(this.value)" autocomplete="off"') ?></label>
</div>
<div class="span4">
		<label>Nombres<?php echo Form::text('nombres') ?></label>
        <label>Apellidos<?php echo Form::text('apellidos') ?></label>
</div>
        
<div class="span4">
        <label>Direccion<?php echo Form::text('direccion') ?></label>
        <label>Teléfono<?php echo Form::text('telefono') ?></label>
</div>


<hr>

<div class="span12">
<a href="#buscarItem" role="button" class="btn btn-info" data-toggle="modal">Buscar Producto</a></div><p>&nbsp;</p>

<div class="span12">
<table width="100%" border="0">
  <tbody>
    <tr>
      <td scope="col"><?php echo Form::hidden('producto.idproducto') ?><label>Cod Producto<?php echo Form::text('producto.cod_producto') ?></label></td>
      <td scope="col"><label>Descripcion<?php echo Form::text('producto.descripcion') ?></label> </td>
      <td scope="col"><label>Cantidad<?php echo Form::number('producto.cantidad','onClick="cambiaCantidad(this.value)"','0') ?></label> </td>
      <td scope="col"><label>Precio Unitario<?php echo Form::text('producto.precio_venta',NULL,'0') ?></label></td>
      <td scope="col"><?php echo Html::link("ventas/facturac#", 'Agregar','id="agregador"class="btn btn-info" data-dismiss="modal" onClick="cargaProducto()"'); ?></td>
    </tr>
  </tbody>
</table>
</div>
<p>&nbsp;</p>
<div class="span12">
<table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th scope="col">Cod Producto</th>
              <th scope="col">Descripción</th>
              <th scope="col">Cantidad</th>
              <th scope="col">Precio Venta</th>
              <th scope="col">Importe</th>
              <th scope="col">Eliminar</th>
            </tr>
          </thead>
          <tbody id="items">
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>
          </tbody>
</table>
</div>

<div class="span8">
<p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>
<table width="100%">
  <tbody>
    <tr>
      <td><label>Efectivo<?php echo Form::text('efe','onKeyup="cambiaRestante()" size="5"','0') ?></label></td>
      <td><label>Tarjeta Débito<?php echo Form::text('tdd','onKeyup="cambiaRestante()" size="5"','0') ?></label></td>
      <td><label>Tarjeta Crédito<?php echo Form::text('tdc','onKeyup="cambiaRestante()" size="5"','0') ?></label></td>
      <td><label>Cestaticket Electrónico<?php echo Form::text('tae','onKeyup="cambiaRestante()" size="5"','0') ?></label></td>
      <td><label>Cestaticket Físico<?php echo Form::text('taf','onKeyup="cambiaRestante()" size="5"','0') ?></label></td>
      <td><label>Restante<?php echo Form::text('restante','size="5"','0') ?></label></td>
    </tr>
  </tbody>
</table>
 <!--<label>Su vuelto<?php echo Form::text('vuelto',NULL,'0') ?></label>-->

</div>    

<div class="span4">
    <div class="subtotal">  
        <label>Subtotal Bs.<?php echo Form::text('subtotal',NULL,'0') ?></label>
        <label>IVA Bs.<?php echo Form::text('iva',NULL,'0') ?></label>
        <label>Total Bs.<?php echo Form::text('total',NULL,'0') ?></label>
    </div>   
</div>

<div class="span12">
	<div class="centrado"><p>&nbsp;</p>
    	<?php echo Js::submit('Guardar Factura','Desea guardar la factura?','btn btn-primary')?>
    </div>
</div>
<?php echo Form::close() ?>




        
<!-- Modal -->
<div id="buscarItem" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <?php echo Html::link('productos/create','<i class="icon-plus"></i> Nuevo Producto','class="btn btn-primary"')?>
      </div>
      <div class="modal-body">
        <div class="span12">
                    <table id="productos" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th scope="col">ID</th>
                          <th scope="col">Código Producto</th>
                          <th scope="col">Código Proveedor</th>
                          <th scope="col">Descripción</th>
                          <th scope="col">Precio Unit</th>
                          <th scope="col">Seleccionar</th>
                        </tr>
                      </thead>
                      <tbody>
                    <?php foreach($listaProductos->items as $producto): ?>
                        <tr>
                          <td><?php echo $producto->idproducto ?></td>
                          <td><?php echo $producto->cod_producto ?></td>
                          <td><?php echo $producto->cod_proveedor ?></td>
                          <td><?php echo $producto->descripcion ?></td>
                          <td><?php echo $producto->precio_venta ?></td>
                          <td><?php echo Html::link("#", 'Agregar','class="btn btn-info" data-dismiss="modal" onClick="buscaProducto('.$producto->idproducto.')"'); ?></td>
                        </tr>
                    <?php endforeach; ?>
                      </tbody>
                    </table>
        </div>
  </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
      </div>
    </div>
<!-- end Modal --> 
 
 
 
<script>
$(document).ready(function() {
    $('#productos').dataTable( {
        "dom": '<"top"f>rt<"bottom"ip><"clear">'
    } );
	
	$("#clientes_identificacion").focus();
	$("#agregador").hide();
	
	$("#direccion").attr("readonly","readonly");
	$("#telefono").attr("readonly","readonly");
	$("#apellidos").attr("readonly","readonly");
	$("#nombres").attr("readonly","readonly");
	$("#producto_cod_producto").attr("readonly","readonly");
	$("#producto_descripcion").attr("readonly","readonly");
	$("#producto_precio_venta").attr("readonly","readonly");
	$("#subtotal").attr("readonly","readonly");
	$("#iva").attr("readonly","readonly");
	$("#total").attr("readonly","readonly");
} );

		function cambiaCantidad(){
			var cantidad = $("#producto_cantidad").val();
			if (cantidad < 1) {
					$("#agregador").hide();
			} else {
				$("#agregador").show();	
			}
		}
		
		function buscaCliente(cedula) {
				$.ajax({
					type: "POST",
					dataType:"json",
					url: "<?php echo PUBLIC_PATH . 'ventas/buscarcliente/' ?>" + cedula,
					success: llegadaCliente
				});
				
				function llegadaCliente(cliente) {
						if (cliente.nombres == "") {
							$("#idcliente").val(cliente.idcliente);
							$("#nombres").val(cliente.nombres);
							$("#apellidos").val(cliente.apellidos); 
							$("#telefono").val(cliente.telefono); 
							$("#direccion").val(cliente.direccion);
						} else {
							$("#idcliente").val(cliente.idcliente);
							$("#nombres").val(cliente.nombres); 
							$("#apellidos").val(cliente.apellidos); 
							$("#telefono").val(cliente.telefono); 
							$("#direccion").val(cliente.direccion); 
						}
				} 
		}
		
		
		function buscaProducto(idproducto) {
				$.ajax({
					type: "POST",
					dataType:"json",
					url: "<?php echo PUBLIC_PATH . 'ventas/buscaritem/' ?>" + idproducto,
					success: llegadaProducto
				});
				
				function llegadaProducto(producto) {
							$("#producto_idproducto").val(producto.idproducto);
							$("#producto_cod_producto").val(producto.cod_producto); 
							$("#producto_descripcion").val(producto.descripcion); 
							$("#producto_precio_venta").val(producto.precio_venta); 
							$("#producto_exento").val(producto.exento); 
				} 
		}
		
		
		function cargaProducto() {
				var idfactemp = $("#idfactemp").val();
				var idproducto = $("#producto_idproducto").val();
				var cantidad = $("#producto_cantidad").val();
				
				$.ajax({
					type: "POST",
					url: "<?php echo PUBLIC_PATH . 'ventas/cargaritem/' ?>" + idfactemp + '/' + idproducto + '/' + cantidad,
					success: llegadaProducto
				});
				
				function llegadaProducto(producto) {
						$("#items").html(producto);
						
						
				} 
		}
		
		function borraProducto(id) {
			confirm("Esta usted seguro?");
			var idfactemp = $("#idfactemp").val();
			$.ajax({
					type: "POST",
					url: "<?php echo PUBLIC_PATH . 'ventas/borraritem/' ?>" + id + '/' + idfactemp,
					success: llegadaProducto
					
			});	
			
			function llegadaProducto(producto) {
				$("#items").html(producto);
			}
		}	
</script>
