<?php View::content(); ?>
<?php
//echo "id: ".  $dato;
//echo var_dump($detalle_elaborados);

if($existe){
    foreach ($detalle_elaborados as $items => $item){
        $idproducto = $item->idproducto;
        $disponible = ($item->disponible == '') ? 0 : $item->disponible;
        $precio_sin_iva = ($item->precio_sin_iva == '') ? 0 : $item->precio_sin_iva; 
        $fe_surtido = $item->fe_surtido;
        $cant_entrada = ($item->cant_entrada == '') ? 0 : $item->cant_entrada; 
    }
    

    $detalle = array (
                    "idreceta" =>  "$idproducto",
                    "disponible" =>    "$disponible",
                    "precio_sin_iva" =>    "$precio_sin_iva",
                    "fe_surtido" =>    "$fe_surtido",
                    "cant_entrada" =>    "$cant_entrada",
            );
            
           
            /*
            $prod_proveedor = array();
            foreach ($productos_proveedor as $items => $item){
                $prod_proveedor[] = array("idproducto" => $item->idproducto, "producto" => $item->marca.'/'.$item->tipo_prod.'/'.$item->cant_empaque);
                //$prod_proveedor[] = array("idproducto" => $item->idproducto, "producto" => $item->marca.'/'.$item->tipo_prod.'/'.$item->cant_empaque); 
            }
            
            $proveedor = array_merge($proveedor, $prod_proveedor);
            //$proveedor = $prod_proveedor;
             * 
             */
            
            //$prod_proveed_JSON_array = json_encode($prod_proveedor);
            
    //$productos_prov = $productos_proveedor;
}else{
     $detalle = array (
    "idreceta" => "",
    "disponible" =>    "",
    "precio_sin_iva" => "",
    "fe_surtido" =>    "",
   "cant_entrada" =>    "",
    );
}

echo json_encode($detalle);
?>