<div class="subnavbar">
  <div class="subnavbar-inner">
    <div class="container">
      <ul class="mainnav">
        <li><?php echo Html::link('index','<i class="icon-desktop"></i><span>Escritorio</span>','title="Clic para ir al inicio"','')?></li>
        <li class="dropdown"><a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" title="Ventas a Clientes"> <i class="icon-pencil"></i>
        <span>Registro</span> <b class="caret"></b></a>
            	<ul class="dropdown-menu">
                    <li><?php echo Html::link('clientes','Clientes')?></li>
                    <li><?php echo Html::link('proveedores','Proveedores')?></li>
                    <li><?php echo Html::link('productos','Productos')?></li>
                    <li><?php echo Html::link('usuarios','Usuarios')?></li>
              	</ul>
        </li>
        <li><?php echo Html::link('preparacion','<i class="icon-fire"></i><span>Preparación</span>','title="Preparación"')?></li>
        <li><?php echo Html::link('punto_venta/create','<i class="icon-shopping-cart"></i><span>Surtido</span>','title="Surtido"')?></li>
        <li><?php echo Html::link('ventas','<i class="icon-check"></i><span>Ventas</span>','title="Ventas"')?></li>
        <li><?php echo Html::link('inventario','<i class="icon-barcode"></i><span>Inventario</span>','title="Inventario"')?></li>
        <li class="dropdown"><a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" title="Administración"> <i class="icon-cogs"></i><span>Admin</span> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><?php echo Html::link('auditoria','Auditoria')?></li>
            <li><?php echo Html::link('mantto','Mantenimiento')?></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /container --> 
  </div>
  <!-- /subnavbar-inner --> 
</div>
<!-- /subnavbar -->