<div class="subnavbar">
  <div class="subnavbar-inner">
    <div class="container">
      <ul class="mainnav">
        <li class="active"><?php echo Html::link('index','<i class="icon-desktop"></i><span>Escritorio</span>','title="Clic para ir al inicio"','')?></li>
        <li><?php echo Html::link('ventas','<i class="icon-file-text"></i><span>Ventas</span>','title="Ventas a Clientes"','')?></li>

        <li class="dropdown"><a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" title="Administración"> <i class="icon-cogs"></i><span>Admin</span> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><?php echo Html::link('usuarios','Usuarios')?></li>
            <li><?php echo Html::link('auditoria','Auditoria')?></li>
            <li><?php echo Html::link('mantto','Mantenimiento')?></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /container --> 
  </div>
  <!-- /subnavbar-inner --> 
</div>
<!-- /subnavbar -->