 <?php if(isset($list)){ ?>
               <table class="table table-striped table-bordered">
                    <tbody>
                      <tr style="background-color: #E5E5E5;">
                        <th>Marca</th> 
                        <th>Tipo Producto</th>  
                        <th>Presentaci&oacute;n</th>
                        <th colspan="2">Acci&oacute;n</th>
                      </tr>
                      <?php 
                      //echo var_dump($list);
                      
                      $n = 0;
                      foreach($list as $items => $item): 
                          $n++; 
                            if($n%2 ==0){
                                    $trClass="light";
                            }else{
                                    $trClass="dark";
                            }
                          ?>
                      <tr class="<?php echo $trClass ?>">
                        <td><?php echo $item->marca ?></td>
                        <td><?php echo $item->tipo_prod ?></td>
                        <td><?php echo $item->presentacion ?></td>
                        <td>
                            <?php echo Html::link("productos/edit/$item->idproducto", Html::img('edit.gif','',array('title'=>'Editar')), 'div_create') ?>
                        </td>
                        <td>
                            <?php echo Html::link("productos/borrar/$item->idproducto", Html::img('delete.png','',array('title'=>'Eliminar', "onclick"=> "return borrar($item->idproducto)"))) ?>

                        </td>
                        <?php //$subtotal = 0; $subtotal = $subtotal + $detalle->importe ?$item->idproducto> ?>
                      </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
    <?php } ?>
<script>   
function borrar(id){
    if(!confirm('Esta seguro de eliminar el registro'))
    {
        return false;
    }else
        return true;
}    
</script>