
<div class="span12"><?php View::content(); ?><br></div>
    <div class="span12">
	<h2><?php echo $titulo;  ?></h2>
        <br>
    </div>

    <div class="span1">&nbsp;</div>
    
    <?php echo Form::open(); // por defecto llama a la misma url ?>
    
    <div class="span3">
    	<fieldset>
            <!--
            <label>Producto
                <?php //echo Form::text('productos.unidad') ?></label>
            -->
            <label>Marca
            <?php
            echo Form::dbSelect('productos.idmarca','marca', array('marcas','getSelect'));
            ?></label>
                
            <label>Tipo de Producto
            <?php
            echo Form::dbSelect('productos.idtipoprod','tipo_prod', array('tipo_productos','getSelect'));
            ?></label>
                
            <label>presentacion
                <?php echo Form::text('productos.presentacion') ?></label>
               
            <label>Unidad de Medida
            <?php
                //echo Form::dbSelect('clientes.idtipodoc','tipo_doc', array('tipo_documentos','getSelect'),'Seleccione',array('onchange'=>'buscarCliente(this)'));
                echo Form::dbSelect('productos.idunidad','unidad', array('unidades','getSelect'));
            ?></label>
            <label>Merma Estimada
                <?php echo Form::text('productos.merma_estimada') ?></label>
		</fieldset>
    </div>
    
    <div class="span1">&nbsp;</div>
    
    <div class="span7">
        <div id="list">
        <?php View::partial('productos/list_productos',FALSE,array('list'=>$list))?>
        </div> 
    </div>       
    
<div class="span12" style="text-align:center"><?php echo Form::submit('Agregar','class="btn btn-primary"') ?></div>
        
<?php echo Form::close() ?> 
