<div class="span3">&nbsp;</div>
<div class="span6">
      <div class="widget">
        <div class="widget-header">
          <h3>Productos</h3>
        </div>
        <!-- /widget-header -->
        <div class="widget-content">
          <div class="shortcuts"> 
              <a href="productos/create" class="shortcut"><i class="shortcut-icon icon-user"></i><span class="shortcut-label">Registro de Productos</span> </a>
              <a href="tipo_productos/create" class="shortcut"><i class="shortcut-icon icon-list-alt"></i><span class="shortcut-label">Tipo de Productos</span> </a>
              <a href="marcas/create" class="shortcut"><i class="shortcut-icon icon-male"></i> <span class="shortcut-label">Marcas</span> </a>
              <a href="unidades/create" class="shortcut"><i class="shortcut-icon icon-male"></i> <span class="shortcut-label">Unidades de Medidas</span> </a>
          </div>
          <!-- /shortcuts --> 
        </div>
        <!-- /widget-content --> 
</div>
<div class="span3">&nbsp;</div>