<div class="span3">&nbsp;</div>
<div class="span6">
      <div class="widget">
        <div class="widget-header">
            <h3>Preparaci&oacute;n</h3>
        </div>
        <!-- /widget-header -->
        <div class="widget-content">
          <div class="shortcuts"> 
              <a href="#" class="shortcut"><i class="shortcut-icon icon-user"></i><span class="shortcut-label">Surtido y Preparaci&oacute;n</span> </a>
              <a href="tipo_preparacion/create" class="shortcut"><i class="shortcut-icon icon-list-alt"></i><span class="shortcut-label">Tipo de Preparaci&oacute;n</span> </a>
              <a href="recetas/create" class="shortcut"><i class="shortcut-icon icon-male"></i> <span class="shortcut-label">Recetas</span> </a>
          </div>
          <!-- /shortcuts --> 
        </div>
        <!-- /widget-content --> 
</div>
<div class="span3">&nbsp;</div>