 <?php if(isset($list)){ ?>
               <table id="listado" class="table table-striped table-bordered" >
                      <thead>
                          <tr>
                            <th>Tipo Documento</th>
                            <th>Descripci&oacute;n</th>
                            <th>Identificador</th>
                            <th colspan="2">Acci&oacute;n</th>
                          </tr>
                      </thead>
                      <tbody>
                      <?php 
                      //echo var_dump($list);
                      $n = 0;
                      foreach($list as $items => $item): 
                          $n++; 
                            if($n%2 ==0){
                                    $trClass="light";
                            }else{
                                    $trClass="dark";
                            }
                          ?>
                      <tr class="<?php echo $trClass ?>">
                        <td><?php echo $item->tipo_doc ?></td>
                        <td><?php echo $item->descripcion ?></td>
                        <td><?php echo $item->identificador ?></td>
                        <td>
                            <?php echo Html::link("tipos_documentos/edit/$item->idtipodoc", Html::img('edit.gif','',array('title'=>'Editar')), 'div_create') ?>
                        </td>
                        <td>
                            <?php echo Html::link("tipos_documentos/borrar/$item->idtipodoc", Html::img('delete.png','',array('title'=>'Eliminar', "onclick"=> "return borrar($item->idtipodoc)"))) ?>

                            <?php //   echo Html::link("tipos_documentos/borrar/#", Html::img('delete.png','',array('title'=>'Eliminar')), array("onclick"=> "return confirm(estas seguro?)")) ?>
                        </td>
                        <?php //$subtotal = 0; $subtotal = $subtotal + $detalle->importe ?$item->idtipodoc> ?>
                      </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
    <?php } ?>
    
<script>

$(document).ready(function() {
    $('#listado').dataTable();
} );

function borrar(id){
    if(!confirm('Esta seguro de eliminar el registro'))
    {
        return false;
     
        //alert('si');
        /*
        var rowSelected=$("body").find('#' + 'c' + id)
        rowSelected.html('<td colspan="4"> <img src="<?php echo PUBLIC_PATH ?>/img/ui/ajax-loader.gif" /> Eliminando ...</td>');
        $.ajax({
         type: "GET",
         url: "<?php //echo PUBLIC_PATH . 'tipos_documentos/borrar/' ?>" + id,
         success:
          function(data){
           $(rowSelected).hide();
           $('#list').html(data);
          }

        });*/
    }else
        return true;
}

</script>
    <?php //echo Tag::js('clientes/tipo_documentos') ?>