
<div class="span12">
    <?php View::content(); ?><br>
	
</div>

<div class="span12">
    <h2><?php echo $titulo;  ?></h2>
    <br>
</div>

    <div class="span2">&nbsp;</div>
    
    <?php echo Form::open(); // por defecto llama a la misma url ?>
    
        <div class="span5">
        
        <label>Condicion de Pago
            <?php echo Form::text('condicionPago.cond_pago') ?></label>
     
            <label>Descripción
            <?php echo Form::text('condicionPago.descripcion') ?></label>
            
            <label>Identificador
            <?php echo Form::text('condicionPago.identificador') ?></label>
            
            <label>Forma de pago </label>
            Pago de Contado<?php echo Form::check('condicionPago.contado','1') ?>
            <br>
            Pago a Credito<?php echo Form::check('condicionPago.credito','1') ?>
            <br>
            Mixto
            <?php echo Form::check('condicionPago.mixto','1') ?>
            
            <br>
            <label>Comentario
            <?php echo Form::textarea('condicionPago.comentario','rows=5') ?></label>
            
    </div>
    
    <div id="list" class="span3" style="width: 300px; height:400px;">
        <?php echo Html::link("condicion_pago/create", 'Crear nuevo') ?>
        <br>
        <?php View::partial('facturas/list_condicion_pago',FALSE,array('list'=>$list))?>
    </div>     
    
    <div class="span2">&nbsp;</div>

    <div class="span12" style="text-align:center">
        <?php echo Form::submit('Actualizar','class="btn btn-primary"') ?>
        <?php echo Form::reset('Cancelar','class="btn btn-primary"') ?>
    </div>
        
<?php echo Form::close() ?> 

