<?php View::content(); ?>
<?php
//echo "id: ".  $dato;
//echo var_dump($ingredientes);
if($existe){
//    $receta = array (
//                    "idreceta" =>  "$recetas->idreceta",
//                    "cant" =>    "$recetas->cant",
//            );
            
            $ingredientes = array();
            foreach ($surtido_prod as $items =>$item){
               $ingredientes[] = array(
                   "idproducto" => $item->idproducto,
                   "idtipoprep" => $item->idtipoprep,
                   "disponible" => $item->disponible,
                   "minima" => $item->minima,
                   "maxima" => $item->maxima,
                   "merma_estimada" => $item->merma_estimada,
                   "cant_porcion_receta" => $item->cant,
                   //"disponible" => $item->disponible,
                   "producto" => $item->marca.'/'.$item->tipo_prod.'/'.$item->cant_empaque,
                   "unidad" => $item->unidad,
                   "idreceta" => $item->idreceta);
               
//                    "id"=>$item->id,
//                    "idunidad" => $item->idunidad,
//                    "minima" => $item->minima,
//                    "maxima" => $item->maxima,
                   
                //$prod_proveedor[] = array("idproducto" => $item->idproducto, "producto" => $item->marca.'/'.$item->tipo_prod.'/'.$item->cant_empaque); 
            }
            
            //$receta = array_merge($receta, $receta_prod);
            
            /*
            $prod_proveedor = array();
            foreach ($productos_proveedor as $items => $item){
                $prod_proveedor[] = array("idproducto" => $item->idproducto, "producto" => $item->marca.'/'.$item->tipo_prod.'/'.$item->cant_empaque);
                //$prod_proveedor[] = array("idproducto" => $item->idproducto, "producto" => $item->marca.'/'.$item->tipo_prod.'/'.$item->cant_empaque); 
            }
            
            $proveedor = array_merge($proveedor, $prod_proveedor);
            //$proveedor = $prod_proveedor;
             * 
             */
            
            //$prod_proveed_JSON_array = json_encode($prod_proveedor);
            
    //$productos_prov = $productos_proveedor;
}else{
     $ingredientes = array (
    "idreceta" => "",
    "cant" =>    "",
    );
}
echo json_encode($ingredientes);
?>