
<div class="span12"><?php View::content(); ?><br></div>

<div class="span12">
	<h2><?php echo $titulo;  ?></h2>

</div>

<div class="span1">&nbsp;</div>
    
    <?php echo Form::open(); // por defecto llama a la misma url ?>
    
    <div class="span3">
		<fieldset>
            <label>Tipo de Condici&oacute;n
            <?php echo Form::text('condicion_prov.condicion') ?></label>
     
            <label>Descripción
            <?php echo Form::text('condicion_prov.descripcion') ?></label>
            
            <label>Identificador
            <?php echo Form::text('condicion_prov.identificador') ?></label>
            
            <br>
            <label>Comentario
            <?php echo Form::textarea('condicion_prov.comentario','rows=5') ?></label>
		</fieldset>      
    </div>
    
    <div class="span1">&nbsp;</div>
    
    <div class="span7">
        <div id="list" class="span3" style="width: 300px; height:400px;">
        <?php View::partial('proveedores/list_condicion_prov',FALSE,array('list'=>$list))?>
        </div> 
    </div>       
    

<div class="span12" style="text-align:center"><?php echo Form::submit('Agregar','class="btn btn-primary"') ?></div>
        
<?php echo Form::close() ?> 

