
<div class="span12">
    <?php View::content(); ?><br>
	
</div>

<div class="span12">
    <h2><?php echo $titulo;  ?></h2>
    <br>
</div>

    <div class="span2">&nbsp;</div>
    
    <?php echo Form::open(); // por defecto llama a la misma url ?>
    
        <div id="div_create" class="span5">
            
            <?php echo Form::hidden('condicion_prov.idcondicion') ?>
            <label>Tipo de Condici&oacute;n
            <?php echo Form::text('condicion_prov.condicion') ?></label>
     
            <label>Descripci&oacute;n
            <?php echo Form::text('condicion_prov.descripcion') ?></label>
            
            <label>Identificador
            <?php echo Form::text('condicion_prov.identificador') ?></label>
            
            <br>
            <label>Comentario
            <?php echo Form::textarea('condicion_prov.comentario','rows=5') ?></label>
            
    </div>
    
    <div id="list" class="span3" style="width: 300px; height:400px;">
        <?php echo Html::link("condicion_prov/create", 'Crear nuevo') ?>
        <br>
        <?php View::partial('proveedores/list_condicion_prov',FALSE,array('list'=>$list))?>
    </div>     
    
    <div class="span2">&nbsp;</div>

    <div class="span12" style="text-align:center">
        <?php echo Form::submit('Actualizar','class="btn btn-primary"') ?>
        <?php echo Form::reset('Cancelar','class="btn btn-primary"') ?>
    </div>
        
<?php echo Form::close() ?> 

