
<div class="span12">
    <?php View::content(); ?><br>
	
</div>

<div class="span12">
    <h2><?php echo $titulo;  ?></h2>
    <br>
</div>

    <div class="span1">&nbsp;</div>
    
    <?php echo Form::open(); // por defecto llama a la misma url ?>
    
    <div class="span5" id="div_create">
    	<fieldset>
            <legend>Crear Condición</legend>
            
            <?php echo Form::hidden('condicion_prov.idcondicion') ?>
            
            <label>Nombre
            <?php echo Form::text('condicion_prov.condicion') ?></label>
     
            <label>Descripci&oacute;n
            <?php echo Form::text('condicion_prov.descripcion') ?></label>
            
            <label>Identificador
            <?php echo Form::text('condicion_prov.identificador') ?></label>
            
            <br>
            <label>Comentario
            <?php echo Form::textarea('condicion_prov.comentario','rows=5') ?></label>
            
         </fieldset>   
    </div>
    
    <div class="span1">&nbsp;</div>
    
    <div id="list" class="span5">
        <?php echo Html::link("condicion_prov/create", 'Crear nuevo', 'class="btn btn-info"') ?>
        <br><br>
        <?php View::partial('proveedores/list_condicion_prov',FALSE,array('list'=>$list))?>
    </div>     
    
    <div class="span2">&nbsp;</div>

    <div class="span12" style="text-align:center">
        <?php echo Form::submit('Actualizar','class="btn btn-primary"') ?>
        <?php echo Form::reset('Cancelar','class="btn btn-cancel"') ?>
    </div>
        
<?php echo Form::close() ?> 

