<h2> Registro de Proveedores </h2>
<?php View::content(); ?>

<?php echo Form::open(); ?>
        <div class="span4">
            <fieldset>
                            <legend>Identificaci&oacute;n</legend>
                                <?php
                                    $ruta = PUBLIC_PATH.'proveedores/buscarProveedor/'; 
                                    
                                    //echo Form::dbSelect('proveedores.idtipodoc','tipo_doc', array('tipo_documentos','getSelect'),'Seleccione',array('onchange'=>'buscarProveedor(this)'));
                                    echo Form::dbSelect('proveedores.idtipodoc','tipo_doc', array('tipo_documentos','getSelect'),'Seleccione' ,array('onchange'=>'accionRif(this)'));
                                    echo Form::text('proveedores.identificacion');
                                ?>

                                <span id="div_digito_rif" style="display: none"> - <?php echo Form::text('digito_rif', array('size'=>'1', 'id'=>'digito_rif',  'maxlenght'=>'1')); ?></span>
                                <?php //echo Html::img('flecha.jpg','',array('title'=>'Actualizar Proveedor','width'=>'30' , "onclick"=> "return actualizarProveedor()")) ?>
                                <?php echo Form::button("Siguiente", array('onclick'=>'buscarProveedor()'))?>
                </fieldset>
        </div>
        
        <div class="span12">&nbsp;</div>
        
        <div class="span3">
                
                 <!--   datos generales-->
                <fieldset>
                    <legend>Datos Generales</legend>
                            <label>Nombre
                            <?php echo Form::hidden('proveedores.idprov') ?>
                            <?php echo Form::text('proveedores.nombre') ?></label>

                            <label>Apellido
                            <?php echo Form::text('proveedores.apellido') ?></label>
                            
                            <label>Direcci&oacute;n
                            <?php echo Form::textarea('proveedores.direccion',array('rows'=>'4','cols'=>'23')) ?> </label> 
                                    
                            <label>Telefono
                            <?php echo Form::text('proveedores.telefono') ?></label>
                            <label>Comentario
                            <?php echo Form::textarea('proveedores.comentario',array('rows'=>'4','cols'=>'23')) ?></label>
                </fieldset> 
     </div>  
     
     <div class="span3">          
                 <fieldset>
                    <legend>Contactos Adicionales</legend>
                            <label>Contacto Alternativo 1
                            <?php echo Form::text('proveedores.contacto1') ?></label>
                            
                            <label>Contacto Alternativo 2 </th>
                            <?php echo Form::text('proveedores.contacto2') ?> </label>
                            
                            <label>Correo Electr&oacute;nico 1
                            <?php echo Form::text('proveedores.correo1') ?> </label>
                            
                            <label>Correo Electr&oacute;nico 2 
                            <?php echo Form::text('proveedores.correo2') ?></label>
                </fieldset>
      </div> 
           

        <!-- SELECCION DE  PRODUCTOS  -->
        <div class="span3">
        	<fieldset>
            			<legend>Selecionar Productos</legend>
                        <label>Tipo de Proveedor
                        <?php //'multiple'=>'false'
                            echo Form::dbSelect('proveedores.idcondicion','condicion', array('condicion_prov','getSelect'),'Seleccione',array('size'=>'9')); //array('size'=>'10')
                        ?></label>
                        <h4>AGREGAR DE PRODUCTOS 
                            <?php echo Html::img('flecha.jpg','',array('title'=>'Actualizar Proveedor','width'=>'50' , "onclick"=> "return agregarProductos()")) ?></h4> 
                       
                           <label>Productos</label>
                            <select name='productos[]' id='productos' multiple="true" size='12'>
                                <?php
                                foreach($productos as $items => $item):
                                    $prod = $item->marca."/".$item->tipo_prod."/".$item->presentacion;
                                    ?>
                                    <option value='<?php echo $item->idproducto ?>'> <?php echo $prod ?>  </option>

                                <?php endforeach; ?>
                            </select>   
             </fieldset> 
        </div>
        
        <!-- PRODUCTOS DEL PROVEEDOR -->
        
        <div class="span3">
        
        	<fieldset>
                         <legend>Productos del proveedor</legend>
                        
                            <div id="list_prod">
                                    <select name='productos_prov[]' id='productos_prov' multiple="true" size='20'>
                                        
                                    </select>
                                <?php //View::partial('proveedores/list_productos_prov',FALSE,array('list'=>$list))?>

                            </div>
            </fieldset>  
        </div>                
 		
        <br>
        
        <div class="span12" style="text-align:center">
            <?php echo Form::button('Guardar', 'onclick="guardarProveedor()" class="btn btn-primary"'); 
              //echo Form::submit('aceptar'); ?> 
        </div>
              
<?php echo Form::close(); ?>


<script>
/* FUNCION QUE BUSCA PROVEEDOR DE ACUERDO A LA IDENTIFICACION*/    
function  buscarProveedor(){
    var identificacion = $('#proveedores_identificacion').val();
    var idtipodoc = $('#proveedores_idtipodoc').val();
    if($('#digito_rif').val() != '')
        identificacion = identificacion + "-" + $('#digito_rif').val();
    
     // Guardamos el select de cursos
     var productos_p = $("#productos_prov");
     
     
    $.ajax({
        dataType:"json",
        type: "POST",
        url: "<?php echo PUBLIC_PATH . 'proveedores/buscarProveedor/'; ?>",
        data: "idtipodoc=" + idtipodoc + "&identificacion=" + identificacion,
        //prod_proveedor
        beforeSend: function () 
        {
            //alert('antes');
            //productos_p.prop('disabled', true);
            // Limpiamos el select
            productos_p.find('option').remove();
            limpiar();
        },
            
        success: function(proveedor){
             productos_p.find('option').remove();
            //$("#prueba").html(html);
            
            $("#proveedores_idprov").val(proveedor.idprov); 
            //$("#proveedores_idtipodoc").val(proveedor.idtipodoc); 
            //$("#proveedores_identificacion").val(proveedor.identificacion);       
            $("#proveedores_nombre").val(proveedor.nombre); 
            $("#proveedores_apellido").val(proveedor.apellido); 
            $("#proveedores_telefono").val(proveedor.telefono); 
            $("#proveedores_direccion").val(proveedor.direccion); 
            $("#proveedores_idcondicion").val(proveedor.idcondicion); 
            $("#proveedores_contacto1").val(proveedor.contacto1);
            $("#proveedores_contacto2").val(proveedor.contacto2);
            $("#proveedores_correo1").val(proveedor.correo1);
            $("#proveedores_correo2").val(proveedor.correo2);
            $("#proveedores_comentario").val(proveedor.comentario);
            
            
            //console.log(JSON.stringify(data));
            $.each(proveedor, function(k,v){
                if(v.producto)
                    productos_p.append('<option value="' + v.idproducto + '">' + v.producto + '</option>');
            })
            productos_p.prop('disabled', false);
            $("#proveedores_nombre").focus();
            
            
        },
        error: function()
            {
                alert('Ocurrio un error en el servidor ..');
                //limpiar();
                //productos_p.find('option').remove();
                //alumnos.prop('disabled', false);
            }
    });
}   

//valida la identificacion
function validarIdentificacion(){
    var valid = true;
    var mensaje = '';
    if($('#proveedores_idtipodoc').val() == ''){
        mensaje = mensaje + 'Seleccione el tipo de documento \t';
        valid = false;
        //return false;
    }
    if($('#proveedores_identificacion').val() == ''){
        //alert('Ingrese el numero de identificacion');
        mensaje = mensaje + 'Ingrese el numero de identificacion \t';
        $('#proveedores_identificacion').focus();
        valid = false;
        //return false;
    }

    if(!valid)
        alert(mensaje);

    return valid;
}

//muestra o no el campo del ultimo de digito de rif en caso que el tipo de documento sea rif
function accionRif(str){
    var tipo_doc = $("#proveedores_idtipodoc option:selected").html();
    if(tipo_doc.toUpperCase() == 'RIF'){
        document.getElementById('div_digito_rif').style.display = '';

    }else{
        document.getElementById('div_digito_rif').style.display = 'none';
        document.getElementById('digito_rif').value = '';
    }

}

//limpia los campos
function limpiar() {
        $("#proveedores_idprov").val(''); 
        //$("#proveedores_idtipodoc").val(''); 
        //$("#proveedores_identificacion").val(''); 
        $("#proveedores_nombre").val(''); 
        $("#proveedores_apellido").val(''); 
        $("#proveedores_telefono").val(''); 
        $("#proveedores_direccion").val(''); 
        $("#proveedores_idcondicion").val('');           
        $("#proveedores_contacto1").val('');
        $("#proveedores_contacto2").val('');
        $("#proveedores_correo1").val('');
        $("#proveedores_correo2").val('');
        $("#proveedores_comentario").val('');
        
        $("#productos_prov").find('option').remove();
        $("#productos_prov").prop('disabled', false);
        //$("#bt_accion").val('');
        //$("#operacion").html('');


        //muestra el formulario
        //document.getElementById('form').style.display = '';
        //listarProductosDelProveedor(); 
}

//agrega al combo el producto seleccionado 
function agregarProductos(){
    var selectedOpts = $('#productos option:selected');
    
    if(selectedOpts.length == 0) {
        alert("Seleccione el producto a agregar");
        return;
    }
    
   // $('#productos_prov').add()
    
    //agregar el producto al combo
    var prod = document.getElementById('productos');
    //var sl = document.getElementById('productos_prov');    
    for (i = 0; i < prod.options.length; i++){
       if(prod.options[i].selected == true){
           //alert(prod.options[i].value);
           //verifica si existe el producto antes de agregarlo
            if(isExistProduct(prod.options[i].value)){
                alert('El proveedor ya tiene agregado este producto');
                return;
                
                //$('#productos_prov').append(prod.options[i]);
                //sl.add(prod.options[i],null);
            }else{
                $('#productos_prov').append('<option value="' + prod.options[i].value + '">' + prod.options[i].text + '</option>');
           
                //$('#productos_prov').append("<option value''> </option>"  prod.options[i].clone());
            }
                
       }
    }
    
    //$('#productos_prov').apen());
    
    
    //var selectedOpts = $('#productos option:selected');
}

function isExistProduct(valor){
    //alert(valor);
    var prod = document.getElementById('productos');
    var prod_v = document.getElementById('productos_prov'); 
    
    var existe = false;
    for (i = 0; i < prod_v.options.length; i++){
        //for (i = 0; i < prod_v.options.length; i++){
        if(prod_v.options[i].value == valor){
            //alert(valor);
            //alert(prod_v.options[i].value);
            //alert('El proveedor ya tiene agregado este producto');
            existe = true;
            //}   
            /*
            if(prod_v.value == valor){

            }*/

           /*if(prod.options[i].selected){
               //alert('sasaas');
               sl.add(prod.options[i],null);
                    */
        }
    }
    return existe;
}

        
        
//funcion para registrar o actualizar el proveedor        
function guardarProveedor(){
    //validar campos
    
    
    var prod_prov = "";
    var prod_v = document.getElementById('productos_prov'); 
    if(!prod_v.options.length > 0){
        alert('Debe agregar por lo menos un producto');
        return;
    }
        
    for (i = 0; i < prod_v.options.length; i++){
        prod_v.options[i].selected = true;
        prod_prov = prod_prov + prod_v.options[i].value + ',';
    }
    
    //alert($("#productos_prov").val());
    //return;
    var idprov = $("#proveedores_idprov").val(); 
    var idtipodoc = $("#proveedores_idtipodoc").val(); 
    var identificacion = $("#proveedores_identificacion").val(); 
    var nombre = $("#proveedores_nombre").val(); 
    var apellido = $("#proveedores_apellido").val(); 
    var telefono = $("#proveedores_telefono").val(); 
    var direccion = $("#proveedores_direccion").val(); 
    var idcondicion = $("#proveedores_idcondicion").val();           
    var contacto1 = $("#proveedores_contacto1").val();
    var contacto2 = $("#proveedores_contacto2").val();
    var correo1 = $("#proveedores_correo1").val();
    var correo2 = $("#proveedores_correo2").val();
    var comentario = $("#proveedores_comentario").val();
    //var accion = (idprov != '' ? 'update' : 'add');                

    var request = 'idprov='+idprov;
    request =  request +'&idtipodoc='+idtipodoc;
    request =  request +'&identificacion='+identificacion;
    request =  request +'&nombre='+nombre;
    request =  request +'&apellido='+apellido;
    request =  request +'&telefono='+telefono;
    request =  request +'&direccion='+direccion;
    request =  request +'&idcondicion='+idcondicion;
    request =  request +'&contacto1='+contacto1;
    request =  request +'&contacto2='+contacto2;
    request =  request +'&correo1='+correo1;
    request =  request +'&correo2='+correo2;
    request =  request +'&comentario='+comentario;
    request =  request +'&productos='+prod_prov;
    //alert(request);
    $.ajax({
        //dataType:"json",
        type: "POST",
        url: "<?php echo PUBLIC_PATH . 'proveedores/actualizarProveedor/'; ?>",
        //data: "idtipodoc=" + idtipodoc + "&identificacion=" + identificacion,
        data: request,
//        beforeSend: function () 
//        {
//            //alert('antes');
//            //productos_p.prop('disabled', true);
//            // Limpiamos el select
//            //productos_p.find('option').remove();
//            //limpiar();
//        },
//        
            
        success: function(html){
            
            $("#prueba").html(html);
            
            //console.log(JSON.stringify(data));
            /*$.each(proveedor, function(k,v){
                if(v.producto)
                    productos_p.append('<option value="' + v.idproducto + '">' + v.producto + '</option>');
            })
            productos_p.prop('disabled', false);
            $("#proveedores_nombre").focus();*/
            
            
        }
//        error: function()
//            {
//                alert('Ocurrio un error en el servidor ..');
//                //limpiar();
//                //productos_p.find('option').remove();
//                //alumnos.prop('disabled', false);
//            }
    }); 
}       
            
   
</script>











