<?php View::content(); ?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<title>Smart Wizard 3 - Basic Example  - a javascript jQuery wizard control plugin</title>

<head>
<?php Tag::css('demo_style') ?>
<?php Tag::css('smart_wizard') ?>

<?php echo Html::includeCss() ?>

<?php echo Tag::js('jquery-2.0.0.min') ?>
<?php echo Tag::js('jquery.smartWizard'); ?>

<!--
<link href="styles/demo_style.css" rel="stylesheet" type="text/css">

<link href="styles/smart_wizard.css" rel="stylesheet" type="text/css">
<script tcargaype="text/javascript" src="js/jquery-2.0.0.min.js"></script>
<script type="text/javascript" src="js/jquery.smartWizard.js"></script>
-->
<script type="text/javascript">
    $(document).ready(function(){
    	// Smart Wizard 	
        $('#wizard').smartWizard();
        $('#wizard').smartWizard();
      
      function onFinishCallback(){
        $('#wizard').smartWizard('showMessage','Finish Clicked');
        //alert('Finish Clicked');
      }     
    });
    
    function alerta(){
        //alert('dddddaa');
    }
</script>

</head>

<table align="center" border="0" cellpadding="0" cellspacing="0">
    <tr>
           <td> 
        <!-- Smart Wizard -->
  		<div id="wizard" class="swMain">
                 <ul>
                <li><a href="#step-1">
                <label class="stepNumber">1</label>
                <span class="stepDesc" style="font-size: 14px;">
                    Incorporaci&oacute;n de <br>Proveedor 
                </span>
                </a></li>
                <li><a href="#step-2">
                <label class="stepNumber">2</label>
                <span class="stepDesc" style="font-size: 14px;">
                    Carga de </br> Productos 
                </span>
                </a></li>
            </ul>
                    
            <div id="step-1">	
            <h2 class="StepTitle">Datos del Proveedor</h2>
            <br>
 
            <?php echo Form::open(); // por defecto llama a la misma url ?>
            <div class="span6">
                <fieldset style="border: 1px solid #ccc;">
                    <table>
                        <tr>
                            <th>Identificaci&oacute;n</th>
                                <td>
                                <?php
                                    $ruta = PUBLIC_PATH.'proveedores/buscarProveedor/'; 
                                    echo Form::hidden('proveedores.ruta','', $ruta);
                                    
                                    //echo Form::dbSelect('proveedores.idtipodoc','tipo_doc', array('tipo_documentos','getSelect'),'Seleccione',array('onchange'=>'buscarProveedor(this)'));
                                    echo Form::dbSelect('proveedores.idtipodoc','tipo_doc', array('tipo_documentos','getSelect'),'Seleccione' ,array('onchange'=>'accionRif(this)'));
                                    echo Form::text('proveedores.identificacion');
                                ?>

                                <span id="div_digito_rif" style="display: none"> - <?php echo Form::text('digito_rif', array('size'=>'1', 'id'=>'digito_rif',  'maxlenght'=>'1')); ?></span>
                                <?php echo Form::button("Siguiente", array('onclick'=>'buscarProveedor()'))?>
                            </td>
                        </tr>
                    </table>
                </fieldset> 
            </div>
        <div  id='form' style='display: '>
                <br>
    
        <span id="operacion" style="font-size: 13px; color: #000; font-weight: bold; ">    </span>
        
        <br>
        <span id="error" style="font-size: 13px; color: #000; font-weight: bold; "> </span>  
        <br>
            
        <table width="100%" border='2'>
            <tr>
                <td>
                <!--   datos generales-->
                <fieldset style="border: 1px solid #ccc;">
                    <legend>Datos Generales</legend>
                    <?php echo Form::hidden('proveedores.idprov') ?>
                    Nombre &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                       <?php echo Form::text('proveedores.nombre') ?>
                    <br>    
                    Apellido &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <?php echo Form::text('proveedores.apellido') ?>
                    <br>
                    Direccion &nbsp;&nbsp;&nbsp;
                    <?php echo Form::textarea('proveedores.direccion','rows=5') ?>          
                    <br>
                    Telefono &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <?php echo Form::text('proveedores.telefono') ?>
                    <br>
                    Comentario &nbsp;
                    <?php echo Form::textarea('proveedores.comentario','rows=5') ?>   
                </fieldset>
                
            </td>
            <td  valign='top'>
                <!-- Contactos Adicionales -->
                <fieldset style="border: 1px solid #ccc;">
                    <legend>Contactos Adicionales</legend>
                    <table>
                        <tr> 
                            <td>
                                Contacto Alternativo 1 &nbsp;
                                <?php echo Form::text('proveedores.contacto1') ?>
                                <br>
                                 Contacto Alternativo 2 &nbsp;
                                <?php echo Form::text('proveedores.contacto2') ?>
                                <br>
                                 Correo Electr&oacute;nico 1
                                 &nbsp;&nbsp;&nbsp;
                                <?php echo Form::text('proveedores.correo1') ?>
                                <br>
                                
                                 Correo Electr&oacute;nico 2 
                                 &nbsp;&nbsp;&nbsp; 
                                <?php echo Form::text('proveedores.correo2') ?> 
                            </td>
                        </tr>
                    </table>
                </fieldset>
                <br>
                    <label>Tipo de Proveedor
                    <?php //'multiple'=>'false'
                        echo Form::dbSelect('proveedores.idcondicion','condicion', array('condicion_prov','getSelect'),'Seleccione'); //array('size'=>'10')
                     ?>
            </td>
      </tr>
       <tr>
            <!--     TIPO DE PROVEEDORES-->
            <td valign='top'>
<!--                    <label>Tipo de Proveedor-->
                    <?php //'multiple'=>'false',
                        //echo Form::dbSelect('proveedores.idcondicion','condicion', array('condicion_prov','getSelect'),'Seleccione'); //array('size'=>'10')
                     ?>
            </td>
            <td></td> 
    </tr>
    </table>    
        
        
  <?php //echo Form::submit('Agregar',array('id'=>'bt_accion')) ?>      
</div>
 
        </div>
        <div id="step-2">
            <h2 class="StepTitle">Carga de Productos</h2>
            <br>
                <fieldset border="1">
                    <legend>Proveedor</legend>
                    <table border='1' width='100%'>
                        <tr>
                            <th align="left">identificacion</th>
                            <th align="left">nombre</th>
                        </tr>
                        <tr>
                            <td id='prov_identificacion'></td>
                            <td id='prov_nombre'></td>
                        </tr>
                    </table>
                </fieldset>
                <hr>
            <table>
                <tr>
                <td valign='top'>
<!--                        <label>Tipo de Proveedor-->
                        <?php //'multiple'=>'false',
                            //echo Form::dbSelect('proveedores.idcondicion','condicion', array('condicion_prov','getSelect'),'Seleccione'); //array('size'=>'10')
                        ?>

                    <br>
                    <?php //echo Form::button('Agregar Producto',array('id'=>'bt_add')) ?>
                    <br>

                    <!-- Listar productos   -->
                    <fieldset>
                    <label><p>SELECCION DE PRODUCTOS</p><b></label>
                    <select name='productos[]' id='productos' multiple="true" size='15'>
                        <?php
                        foreach($productos as $items => $item):
                            $prod = $item->marca."/".$item->tipo_prod."/".$item->presentacion;
                            ?>
                            <option value='<?php echo $item->idproducto ?>'> <?php echo $prod ?>  </option>

                        <?php endforeach; ?>
                    </select>   
                    </fieldset>    

                </td>

                <!--   productos del proveedor -->
                <td valign='top'>

                    <!-- Listar productos   -->
                    <fieldset>
                    <label>Productos distribuidos por este proveedor<b></label>
                    <div id="list_prod">
                        <?php //View::partial('proveedores/list_productos_prov',FALSE,array('list'=>$list))?>

                    </div>

                    </fieldset>  

                </td>           

            </tr>
        </table>    
            
                     
       </div> 
         
       
    </div>
<!-- End SmartWizard Content -->  		
 		
</td></tr>
</table>
 <?php echo Form::close() ?>   		
</body>
</html>


<script>
    
    $(document).ready(function() {
    //$('#bt_add').click(function(e) {
    /* para agregar productos*/
    $('#productos').change(function(e) {
        var selectedOpts = $('#productos option:selected');
        
        if (selectedOpts.length == 0) {
            alert("Seleccione el producto");
            return;
        }
        
        var idprod = selectedOpts.val();
        var idprov = $("#proveedores_idprov").val();
        var identificacion = $("#proveedores_identificacion").val();
        
        if((idprov == '') && (identificacion == '')){
            alert("El proveedor no esta registrado");
            return;
        }
        alert("idprod=" + idprod + "&idprov=" + idprov);
        $.ajax({
        //dataType:"json",
        type: "POST",
        url: "<?php echo PUBLIC_PATH . 'proveedores/agregarProducto/'; ?>",
        data: "idprod=" + idprod + "&idprov=" + idprov, // + "&identificacion="+identificacion,
        //success: cargarDatos
        
        success: function(html){
            $("#list_prod").html(html);
            
            //alert($("#list_prod").find( "span" ).text());
            var valor = $("#list_prod").find( "span" ).text();
            alert(valor);
            
            if(valor == 'true'){
                $(selectedOpts).remove();
            }
        }
        });
    });
    
    
});



    function accionRif(str){
       var tipo_doc = $("#proveedores_idtipodoc option:selected").html();
       if(tipo_doc.toUpperCase() == 'RIF'){
           document.getElementById('div_digito_rif').style.display = '';
           
       }else{
           document.getElementById('div_digito_rif').style.display = 'none';
           document.getElementById('digito_rif').value = '';
       }
        
    }
    
    function  buscarProveedor(){
        if($('#proveedores_idtipodoc').val() == ''){
            alert('Seleccione el tipo de documento');
            return false;
        }
        if($('#proveedores_identificacion').val() == ''){
            alert('Ingrese el numero de identificacion');
            return false;
        }
            
	var identificacion = $('#proveedores_identificacion').val();
        var idtipodoc = $('#proveedores_idtipodoc').val();
        if($('#digito_rif').val() != '')
            identificacion = identificacion + "-" + $('#digito_rif').val();
        
        
        $.ajax({
        dataType:"json",
        type: "POST",
        url: "<?php echo PUBLIC_PATH . 'proveedores/buscarProveedor/'; ?>",
        data: "idtipodoc=" + idtipodoc + "&identificacion=" + identificacion,
        success: cargarDatos 
        /*
        success: function(html){
            $("#form").html(html);
        }*/
        
       
        });
        
        
        function cargarDatos(proveedor) {
                //limpiar los campos
                limpiar(); 
                
                $("#proveedores_idprov").val(proveedor.idprov); 
                //$("#proveedores_idtipodoc").val(proveedor.idtipodoc); 
                //$("#proveedores_identificacion").val(proveedor.identificacion);              
                $("#proveedores_nombre").val(proveedor.nombre); 
                $("#proveedores_apellido").val(proveedor.apellido); 
                $("#proveedores_telefono").val(proveedor.telefono); 
                $("#proveedores_direccion").val(proveedor.direccion); 
                $("#proveedores_idcondicion").val(proveedor.idcondicion); 
                
                $("#proveedores_contacto1").val(proveedor.contacto1);
                $("#proveedores_contacto2").val(proveedor.contacto2);
                $("#proveedores_correo1").val(proveedor.correo1);
                $("#proveedores_correo2").val(proveedor.correo2);
                $("#proveedores_comentario").val(proveedor.comentario);
                
                $("#proveedores_nombre").focus();
            
                $("#bt_accion").val(proveedor.bt_accion);
                $("#operacion").html(proveedor.operacion);
                
                
                //muestra el formulario
                document.getElementById('form').style.display = '';
                listarProductosDelProveedor(); 
        }
        
        function listarProductosDelProveedor(){
            
           var idprov = $('#proveedores_idprov').val(); 
           $.ajax({
            //dataType:"json",
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'proveedores/listarProductosProveedor/'; ?>",
            data: "identificacion=" + identificacion,
            //data: "idprov=" + idprov,
            //success: cargarDatos

            success: function(html){
                //$("#list_prod").html('');
                $("#list_prod").html(html);
                //$(selectedOpts).remove();
            }
            }); 
        }
        //funcion para limpiar los campos
        function limpiar() {
                $("#proveedores_idprov").val(''); 
                //$("#proveedores_idtipodoc").val(''); 
                //$("#proveedores_identificacion").val(''); 
                $("#proveedores_nombre").val(''); 
                $("#proveedores_apellido").val(''); 
                $("#proveedores_telefono").val(''); 
                $("#proveedores_direccion").val(''); 
                $("#proveedores_idcondicion").val('');           
                $("#proveedores_contacto1").val('');
                $("#proveedores_contacto2").val('');
                $("#proveedores_correo1").val('');
                $("#proveedores_correo2").val('');
                $("#proveedores_comentario").val('');
                $("#bt_accion").val('');
                $("#operacion").html('');
                
                
                //muestra el formulario
                document.getElementById('form').style.display = '';
                //listarProductosDelProveedor(); 
        }
    }  
    
    function actualizarProveedor(){
        var idprov = $("#proveedores_idprov").val(); 
        var idtipodoc = $("#proveedores_idtipodoc").val(); 
        var identificacion = $("#proveedores_identificacion").val(); 
        var nombre = $("#proveedores_nombre").val(); 
        var apellido = $("#proveedores_apellido").val(); 
        var telefono = $("#proveedores_telefono").val(); 
        var direccion = $("#proveedores_direccion").val(); 
        var idcondicion = $("#proveedores_idcondicion").val();           
        var contacto1 = $("#proveedores_contacto1").val();
        var contacto2 = $("#proveedores_contacto2").val();
        var correo1 = $("#proveedores_correo1").val();
        var correo2 = $("#proveedores_correo2").val();
        var comentario = $("#proveedores_comentario").val();
        var accion = (idprov != '' ? 'update' : 'add');                

        var request = 'idprov='+idprov;
            request =  request +'&idtipodoc='+idtipodoc;
            request =  request +'&identificacion='+identificacion;
            request =  request +'&nombre='+nombre;
            request =  request +'&apellido='+apellido;
            request =  request +'&telefono='+telefono;
            request =  request +'&direccion='+direccion;
            request =  request +'&idcondicion='+idcondicion;
            request =  request +'&contacto1='+contacto1;
            request =  request +'&contacto2='+contacto2;
            request =  request +'&correo1='+correo1;
            request =  request +'&correo2='+correo2;
            request =  request +'&comentario='+comentario;
            request =  request +'&accion='+accion;
        //var ruta = $("#proveedores_ruta").val();
        //alert('enttra');
        
        $.ajax({
        //dataType : "html",
        type: "POST",
        url: "<?php echo PUBLIC_PATH . 'proveedores/actualizarProveedor/'; ?>",
        data: request,
        
            success: function(html){
                    
                    
                    //alert(html);
                    $("#operacion").html(html);
                    //se carga en la pantalla de 
                    $("#prov_identificacion").html(identificacion);
                    $("#prov_nombre").html(nombre +" "+ apellido);
                    
                    //listarProductosDelProveedor();
                    
                    
                    /*
                    alert($("#operacion").find( "span" ).text());
                    var valor = $("#operacion").find( "span" ).text();
                    if(valor.text() == 'true'){
                        alert('es true');
                    }*/
                    
            }
        });
        //listarProductosDelProveedor();
        
        //return
    }               
        
        //});
        /*
        if(num_identif != ''){
            var rowSelected=$("body").find('#' + 'form' )
            //rowSelected.html('<td colspan="4"> <img src="<?php //echo PUBLIC_PATH ?>/img/ui/ajax-loader.gif" /> Eliminando ...</td>');
            rowSelected.html('<span> <img src="<?php //echo PUBLIC_PATH ?>/img/ui/ajax-loader.gif" /> Carcgando ...</span>');
            $.ajax({
            type: "POST",
            dataType:"html",
            //type: "GET",
            url: "<?php //echo PUBLIC_PATH . 'proveedores/tipos' ?>",
            success:
            function(data){
                $(rowSelected).hide();
                $('#form').html(data);
            }
            });
         }else{
            alert('Debe ingresar el numero de identificacion');
            document.getElementById("proveedores_identificacion").focus;
            return;
         }
        
        */
        
       /*
        for(i=0; i<theForm.elements.length; i++){
            var alertText = ""
                alertText = "Element id: " + theForm.elements[i].id + "\n"
               
                alertText = "Element Name: " + theForm.elements[i].name + "\n"
                
                alertText += "Element Type: " + theForm.elements[i].type + "\n"

                if(theForm.elements[i].type == "text" || theForm.elements[i].type == "textarea" || theForm.elements[i].type == "button"){
                alertText += "Element Value: " + theForm.elements[i].value + "\n"
                }
                else if(theForm.elements[i].type == "checkbox"){
                alertText += "Element Checked? " + theForm.elements[i].checked + "\n"
                }
                else if(theForm.elements[i].type == "select-one"){
                alertText += "Selected Option's Text: " + theForm.elements[i].options[theForm.elements[i].selectedIndex].text + "\n"
                }
            alert(alertText)
        }
        */
   
        /*
        var rowSelected=$("body").find('#' + 'identificacion');
        alert(rowSelected.val);
        alert('entro');*/

        /*
        var rowSelected=$("body").find('#' + 'identificacion' )


        rowSelected.html('<td colspan="4"> <img src="<?php //echo PUBLIC_PATH ?>/img/ui/ajax-loader.gif" /> Eliminando ...</td>');
        $.ajax({
        type: "GET",
        url: "<?php //echo PUBLIC_PATH . 'tipos_documentos/borrar/' ?>" + id,
        success:
        function(data){
        $(rowSelected).hide();
        $('#list').html(data);
        }

        });*/
        /*if(document.getElementByName('proveedores[identificacion]').value == ''){
            alert('esta ');
        }*/
        
   


    </script>
