
<div class="span12"><?php View::content(); ?><br></div>
    <div class="span12">
	<h2><?php echo $titulo;  ?></h2>
        <br>
    </div>

    <div class="span1">&nbsp;</div>
    
    <?php echo Form::open(); // por defecto llama a la misma url ?>
    
    <div class="span3">
        <fieldset>
        	<legend>Crear Marca</legend>
                <label>Nombre
                <?php echo Form::text('marcas.marca') ?></label>
         
                <label>Descripción
                <?php echo Form::text('marcas.descripcion') ?></label>
                
                <label>Identificador
                <?php echo Form::text('marcas.identificador') ?></label>
                
                <br>
                <label>Comentario
                <?php echo Form::textarea('marcas.comentario','rows=5') ?></label>
       </fieldset> 
       
       <div class="centrado"><?php echo Form::submit('Agregar','class="btn btn-primary"') ?></div>
           
    </div>
    
    <div class="span1">&nbsp;</div>
    
    <div class="span7">
        <div id="list">
        <?php View::partial('productos/list_marcas',FALSE,array('list'=>$list))?>
        </div> 
    </div>       
           
<?php echo Form::close() ?> 

