
<div class="span12">
    <?php View::content(); ?><br>
	
</div>

<div class="span12">
    <h2><?php echo $titulo;  ?></h2>
    <br>
</div>

<?php echo Form::open(); // por defecto llama a la misma url ?>

    <div class="span1">&nbsp;</div>

    <div class="span3" id="div_create" >
    
        <fieldset>
            
            <?php echo Form::hidden('marcas.idmarca') ?>
            <label>Marcas
            <?php echo Form::text('marcas.marca') ?></label>
     
            <label>Descripción
            <?php echo Form::text('marcas.descripcion') ?></label>
            
            <label>Identificador
            <?php echo Form::text('marcas.identificador') ?></label>
            
            <br>
            <label>Comentario
            <?php echo Form::textarea('marcas.comentario','rows=5') ?></label>
            
        </fieldset>
        
	</div>

	<div class="span1"></div>
    
    <div id="list" class="span7">
        <?php echo Html::link("marcas/create", 'Crear nuevo','class="btn btn-info"') ?>
        <br><br>
        <?php View::partial('productos/list_marcas',FALSE,array('list'=>$list))?>
    </div>     
    
    <div class="span12" style="text-align:center">
        <?php echo Form::submit('Actualizar','class="btn btn-primary"') ?>
        <?php echo Form::reset('Cancelar','class="btn btn-cancel"') ?>
    </div>
        
<?php echo Form::close() ?> 

