<div class="span3">&nbsp;</div>
<div class="span6">
      <div class="widget">
        <div class="widget-header">
          <h3>Inventario</h3>
        </div>
        <!-- /widget-header -->
        <div class="widget-content">
          <div class="shortcuts"> 
              <a href="facturas/create" class="shortcut"><i class="shortcut-icon icon-user"></i><span class="shortcut-label">Ingreso de Facturas y Productos</span> </a>
              <a href="#" class="shortcut"><i class="shortcut-icon icon-list-alt"></i><span class="shortcut-label">Stock</span> </a>
          </div>
          <!-- /shortcuts --> 
        </div>
        <!-- /widget-content --> 
</div>
<div class="span3">&nbsp;</div>

