 <?php if(isset($list)){ ?>
               <table class="table table-striped table-bordered">
                    <tbody>
                      <tr style="background-color: #E5E5E5;">  
                        <th>Tipo de Preparaci&oacute;n</th>
                        <th colspan="2">Acci&oacute;n</th>
                      </tr>
                      <?php 
                      $n = 0;
                      foreach($list as $items => $item): 
                          $n++; 
                            if($n%2 ==0){
                                    $trClass="light";
                            }else{
                                    $trClass="dark";
                            }
                          ?>
                      <tr class="<?php echo $trClass ?>">
                        <td><?php echo $item->tipo_prep ?></td>
                        <td>
                            <?php echo Html::link("tipo_preparacion/edit/$item->idtipoprep", Html::img('edit.gif','',array('title'=>'Editar')), 'div_create') ?>
                        </td>
                        <td>
                            <?php echo Html::link("tipo_preparacion/borrar/$item->idtipoprep", Html::img('delete.png','',array('title'=>'Eliminar', "onclick"=> "return borrar($item->idtipoprep)"))) ?>
                        </td>
                        <?php //$subtotal = 0; $subtotal = $subtotal + $detalle->importe ?$item->idtipoprep> ?>
                      </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
    <?php } ?>
<script>   
function borrar(id){
    if(!confirm('Esta seguro de eliminar el registro'))
    {
        return false;
    }else
        return true;
}    
</script>