<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Escritorio Oasis Restaurant & Café</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<?php Tag::css('bootstrap.min') ?>
<?php Tag::css('bootstrap-responsive.min') ?>
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600"
        rel="stylesheet">
<?php Tag::css('font-awesome') ?>
<?php Tag::css('style') ?>
<?php Tag::css('pages/signin') ?>
<?php echo Html::includeCss() ?>
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container"> <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span
                    class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span> </a>
                    <?php echo Html::link('index/index','Oasis Restaurant & Café','class="brand"')?>
      
    </div>
    <!-- /container --> 
  </div>
  <!-- /navbar-inner --> 
</div>
<!-- /navbar -->


<div class="main">
  <div class="main-inner">
    <div class="container">
      <div class="row">
          <?php View::content(); ?>
      </div>
      <!-- /row --> 
    </div>
    <!-- /container --> 
  </div>
  <!-- /main-inner --> 
</div>
<!-- /main -->

<?php View::partial('footer')?>
<!-- Le javascript
================================================== --> 
<!-- Placed at the end of the document so the pages load faster --> 
<?php echo Tag::js('jquery-1.7.2.min') ?>
<?php echo Tag::js('excanvas.min') ?>
<?php echo Tag::js('chart.min') ?> 
<?php echo Tag::js('bootstrap') ?>
<?php echo Tag::js('full-calendar/fullcalendar.min') ?>
<?php echo Tag::js('base') ?>
</body>
</html>
