
<div class="span12">
    <?php View::content(); ?><br>
	
</div>

<div class="span12">
    <h2><?php echo $titulo;  ?></h2>
    <br>
</div>

    <div class="span2">&nbsp;</div>
    
    <?php echo Form::open(); // por defecto llama a la misma url ?>
    
        <div id="div_create" class="span5">
            
            <?php echo Form::hidden('tipo_preparacion.idtipoprep') ?>
            <label>Tipo de Produto
            <?php echo Form::text('tipo_preparacion.tipo_prep') ?></label>
     
            <label>Descripción
            <?php echo Form::text('tipo_preparacion.descripcion') ?></label>
            
            <label>Identificador
            <?php echo Form::text('tipo_preparacion.identificador') ?></label>
            
            <br>
            <label>Comentario
            <?php echo Form::textarea('tipo_preparacion.comentario','rows=5') ?></label>
            
    </div>
    
    <div id="list" class="span3" style="width: 300px; height:400px;">
        <?php echo Html::link("tipo_preparacion/create", 'Crear nuevo') ?>
        <br>
        <?php View::partial('preparacion/list_tipo_preparacion',FALSE,array('list'=>$list))?>
    </div>     
    
    <div class="span2">&nbsp;</div>

    <div class="span12" style="text-align:center">
        <?php echo Form::submit('Actualizar','class="btn btn-primary"') ?>
        <?php echo Form::reset('Cancelar','class="btn btn-primary"') ?>
    </div>        
<?php echo Form::close() ?> 

