
<div class="span12">
    <?php View::content(); ?><br>
	
</div>

<div class="span12">
    <h2><?php echo $titulo;  ?></h2>
    <br>
</div>



    <div class="span1">&nbsp;</div>
    
    <?php echo Form::open(); // por defecto llama a la misma url ?>
    
    <div class="span3" id="div_create">
    
    		<fieldset>
            <legend>Modificar Unidad de Medida</legend>
            <?php echo Form::hidden('unidades.idunidad') ?>
            <label>Unidad de Medida
            <?php echo Form::text('unidades.unidad') ?></label>
     
            <label>Descripción
            <?php echo Form::text('unidades.descripcion') ?></label>
            
            <label>Identificador
            <?php echo Form::text('unidades.identificador') ?></label>
            
            <br>
            <label>Comentario
            <?php echo Form::textarea('unidades.comentario','rows=5') ?></label>
            
           </fieldset>
            
    </div>
    
    <div class="span1">&nbsp;</div>
    
    <div id="list" class="span4">
        <?php echo Html::link("unidades/create", 'Crear nuevo', 'class=btn btn-info') ?>
        <br><br>
        <?php View::partial('productos/list_unidades',FALSE,array('list'=>$list))?>
    </div>     
    
    <div class="span12" style="text-align:center">
        <?php echo Form::submit('Actualizar','class="btn btn-primary"') ?>
        <?php echo Form::reset('Cancelar','class="btn btn-cancel"') ?>
    </div>
        
<?php echo Form::close() ?> 

